apiVersion: apps/v1
kind: Deployment
metadata:
  name: dripper
  labels:
    app: dripper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dripper
  template:
    metadata:
      labels:
        app: dripper
    spec:
      containers:
        - name: dripper
          image: ghcr.io/somethingsoftware/web-dripper:latest
          imagePullPolicy: Always
          imagePullSecrets:
            - name: ghcr-pull-secret
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 600
          env:
          - name: APP_ENV
            value: "prod"
          - name: MAIN_HOST
            value: "cadencereader.com"
          - name: MAIN_HTTP_PORT
            value: "8080"
          - name: DRIPPER_HOST
            value: "dripper.cadencereader.com"
          - name: DRIPPER_HTTP_PORT
            value: "8081"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: example-db-app
                key: uri
          - name: MIGRATION_FOLDER
            value: "/migrations"          
          - name: VIEW_FOLDER
            value: "/views"
