name: Tailscale k3s SSH Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Tailscale
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:nuc-k3s
    
    - name: Start Deployment
      uses: FarisZR/tailscale-ssh-deploy@v1
      with:
        remote_host: github@100.87.250.127
        directory: generated
        remote_destination: /users/sam/git/somethingsoftware/cadencereader # TODO move to /var/www ?
        post_upload_command: echo thats it
